name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Install Software
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install -y gcc grep sed gawk autoconf	automake bison bzip2 flex texinfo libtool-bin	git doxygen
          sudo apt install -y gperf make python texinfo unrar python3-pip help2man libncurses5-dev sudo unzip wget
      - 
        name: Install crosstool-ng 
        run: |
          git clone --depth=1 https://github.com/crosstool-ng/crosstool-ng.git
          cd crosstool-ng
          ./bootstrap 
          ./configure
          make 
          sudo make install
          cd .. >> /dev/null
          rm -rf crosstool-ng
      - 
        name: build bytebox-aarch64-defconfig
        run: |
          cp bytebox-aarch64-defconfig .config
          ct-ng build
      - 
        name: build bytebox-arm-defconfig
        run: |
          cp bytebox-arm-defconfig .config
          ct-ng build
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mengdemao/bytebox_compiler:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
